### ISSUE TITLE
No module named ligsiangl-service

### ISSUE THREAD

**Issue by LithiumNL** [throneless-tech/libsignal-service-javascript#9]
Hi,

I am probably doing something wrong but i don't know what.
After creating a new clean dir I npm installed your lib: npm install --save @throneless/libsignal-service
After that I used a terminal to open node and typed: const Signal = require('libsignal-service')
Imidiatly after that i get the error module not found. After looking into the nod_modules folder i can see the module. What am i doing wrong? I was hoping that someone could help me out with this silly question.

**Comment by michaelkebe** [comment]
This works for me:

`const Signal = require('@throneless/libsignal-service');`
